server:
  port: 8090
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: 123456
    key-store: keystore.p12
spring:
  profiles:
    active: dev
    include: secret
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false
  security:
    user:
      name: user1
      password: 1234
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
logging:
  level:
    org.example.springbooturl: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

custom:
  jwt:
    secretKey: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890
  accessToken:
    expirationSec: '#{60*60}'
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:5173"
    backUrl: "https://${custom.dev.cookieDomain}:${server.port}"
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
  temp:
    dirPath: c:/temp/surl_dev/temp
  genFile:
    dirPath: c:/temp/surl_dev
  meilisearch:
    host: "http://localhost:7700"
    apiKey: "masterKey"